#!/usr/bin/env python3
#Created by Georgi Dimitrov

import argparse
from os import system
import sys

####important 
####first  parse=argparse.ArgumentParser()
####second parse.add_argument
####third  args=parse.parse_args
####That is exampel how to use argparse module

parse=argparse.ArgumentParser()

parse.add_argument('-ipad', '--ipaddress', action='store_true')
parse.add_argument('-iprs', '--iproutshow', action='store_true')
parse.add_argument('-iplinks', action='store_true')


args=parse.parse_args()

if args.ipaddress:
        system('ip a s')
elif args.iproutshow:
    system('ip r s')
elif args.iplinks:
	system('ip link show')
else:
        print('Lebed')
        sys.exit()
